# Deploy on remote server
deployScriptDev: &deployScriptDev
  - apt-get update && apt-get -qq install ssh openssh-client
  - ssh -i  ~/.ssh/config infodevelop@informagedevelop.com -p 60606 "cd /home/infodevelop/public_html/ciudadana && rm -R vendor 2> /dev/null && rm package-lock.json 2> /dev/null && rm public/js/app.js 2> /dev/null && rm public/css/app.css 2> /dev/null && rm  storage/api-docs/api-docs.json 2> /dev/null && git pull origin master && /opt/cpanel/ea-php72/root/usr/bin/php -d memory_limit=-1 /opt/cpanel/composer/bin/composer install && /opt/cpanel/ea-nodejs10/bin/npm install --scripts-prepend-node-path && /opt/cpanel/ea-nodejs10/bin/npm run-script development --scripts-prepend-node-path && chmod -R 777 storage/framework/cache/ && /opt/cpanel/ea-php72/root/usr/bin/php artisan config:cache && /opt/cpanel/ea-php72/root/usr/bin/php artisan migrate && /opt/cpanel/ea-php72/root/usr/bin/php artisan db:seed && /opt/cpanel/ea-php72/root/usr/bin/php artisan l5-swagger:generate && /opt/cpanel/ea-php72/root/usr/bin/php artisan storage:link"

pipelines:
  branches:
    master:
      - step:
          name: Deploy
          script: *deployScriptDev
